name: nsd_platform_interface
description: Flutter network service discovery plugin (platform interface submodule - will be installed with the parent plugin).
version: 2.0.0
repository: https://github.com/sebastianhaberey/nsd/tree/main/nsd_platform_interface
issue_tracker: https://github.com/sebastianhaberey/nsd/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.7
  uuid: ^4.2.1
  provider: ^6.1.1
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
