name: nsd_platform_interface
description: Flutter network service discovery plugin (platform interface submodule - will be installed with the parent plugin).
version: 2.1.1
repository: https://github.com/sebastianhaberey/nsd/tree/main/nsd_platform_interface
issue_tracker: https://github.com/sebastianhaberey/nsd/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  uuid: ^4.5.2
  provider: ^6.1.5+1
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
