name: nsd
description: A Flutter plugin for network service discovery and registration (aka NSD / DNS-SD / Bonjour / mDNS).
version: 4.0.0
repository: https://github.com/sebastianhaberey/nsd/tree/main/nsd
issue_tracker: https://github.com/sebastianhaberey/nsd/issues
#publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # production
  nsd_android: ^2.1.0
  nsd_ios: ^2.0.0
  nsd_macos: ^2.0.0
  nsd_platform_interface: ^2.1.0
  nsd_windows: ^3.0.0

#  # development
#  nsd_android:
#    path: ../nsd_android
#  nsd_ios:
#    path: ../nsd_ios
#  nsd_macos:
#    path: ../nsd_macos
#  nsd_windows:
#    path: ../nsd_windows
#  nsd_platform_interface:
#    path: ../nsd_platform_interface

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        default_package: nsd_android
      ios:
        default_package: nsd_ios
      macos:
        default_package: nsd_macos
      windows:
        default_package: nsd_windows
