name: example
description: Example application for the Flutter nsd plugin.
homepage: https://github.com/sebastianhaberey/nsd
version: 2.1.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  nsd:
    path: ../
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  flutter_speed_dial: ^7.0.0
  uuid: ^4.5.2
  shelf: ^1.4.2

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
