name: example
description: Example application for the Flutter nsd plugin.
homepage: https://github.com/sebastianhaberey/nsd
version: 2.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  nsd:
    path: ../
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  flutter_speed_dial: ^7.0.0
  uuid: ^4.2.1
  shelf: ^1.4.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
