name: example
description: Example application for the Flutter nsd plugin.
homepage: https://github.com/sebastianhaberey/nsd
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  nsd:
    path: ../
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  flutter_speed_dial: ^6.2.0
  uuid: ^4.2.1
  shelf: ^1.4.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
