name: example
description: Example application for the Flutter nsd plugin.
homepage: https://github.com/sebastianhaberey/nsd
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  nsd:
    path: ../
  cupertino_icons: ^1.0.4
  provider: ^6.0.2
  flutter_speed_dial: ^5.1.0
  uuid: ^3.0.6
  shelf: ^1.3.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
