# see https://www.linkedin.com/pulse/github-actions-flutter-app-moataz-nabil
# see https://github.com/felangel/bloc/blob/master/.github/workflows/flutter_bloc.yaml

name: Platform Tests

on:
  workflow_dispatch:
  push:
    paths:
      - "nsd_platform_interface/**"

env:
  flutter_version: '3.38.5'

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: nsd_platform_interface

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}

      - name: Set up Flutter environment
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # 'dev', 'alpha', 'stable'
          flutter-version: ${{ env.flutter_version }}

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Verify code format
        run: dart format --set-exit-if-changed .

      - name: Analyze code
        run: flutter analyze .

      - name: Run tests
        run: flutter test --no-pub
